config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  resources :users 
  resources :tweets
  resources :likes, only: [:create, :destroy]

  root 'tweets#index'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy
    has_many :like_users, source: :user, through: :likes
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :like_tweets, source: :tweet, through: :likes
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
        def current_user
            if session[:login_uid]
                User.find_by(uid: session[:login_uid])
            end
        end
        
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        #user = User.find_by(uid: session[:login_uid])
        #user.like_tweets << tweet
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        #user = User.find_by(uid: session[:login_uid])
        #tweet.likes.find_by(user_id: user.id).destroy
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render "login"
  end
  def login
    user = User.find_by(uid: params[:uid])
    if user != nil
      login_password = BCrypt::Password.new(user.pass)
      if login_password == params[:pass]
        session[:login_uid]=user.uid
        redirect_to root_path
      else
        render "login"
      end
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end
  
  def create
    tweet = Tweet.new(message: params[:tweet][:message])
    tweet.save
    redirect_to root_path
  end
  
  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  #def create
  #  p = BCrypt::Password.create(params[:user][:pass])
  #  user=User.new(uid: params[:user][:uid], pass: p ,age: params[:user][:age])
  #  user.save
  #  redirect_to users_path
  #end
  def create
    @user = User.new(
    uid: params[:user][:uid],
    password: params[:user][:password],
    password_confirmation: params[:user][:password_confirmation])
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5New</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

app/views/tweets/index.html.erb
<% if current_user %>
        <% @tweets.each do |e| %>
    <p>
        <%= e.message %>
        <%= link_to "削除", tweet_path(e), data: {"turbo-method": :delete} %>
        <%= link_to 'いいね', likes_path(tweet_id: e.id), data: {"turbo-method": :post} %>
        <%= link_to 'いいね削除', like_path(e), data: {"turbo-method": :delete} %>
    </p>
    
    <hr>
    
    <% end %>
    <%= form_for @tweet, url: {action: :create} do |f| %>
        <%= f.label :message, 'message' %>
        <%= f.text_field :message %>
        <%= f.submit 'ツイート' %>
    <% end %>
    
<% else %>
    <p>ログインしてください。</p>
<% end %>


<hr>

<% if current_user %>
    <p><%= link_to 'ログアウト',top_logout_path %></p>
<% else %>
    <p><%= link_to 'ログイン',top_main_path %></p>
<% end %>

<%= link_to 'ユーザ一覧',users_path %>

app/views/users/index.html.erb
<% @users.each do |e| %>
<p>
    UID: <%= e.uid %>
    PASS: <%= e.pass %>
    AGE: <%= e.age %>
    <%= link_to "削除", user_path(e), data: {"turbo-method": :delete} %>
</p>

<% end %>

<%= link_to "新規追加",new_user_path %>
<hr>
<%= link_to 'ツイート一覧',tweets_path %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: :create} do |f| %>
    <%= f.label :uid, 'UID' %>
    <%= f.text_field :uid %>
    <p>
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password %>
    </p>
    <p>
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation %>
    </p>
    <%= f.label :age, 'AGE' %>
    <%= f.text_field :age %>
    <%= f.submit '登録' %>
<% end %>